name: Pull Request

on:
  pull_request:
    paths:
      - '**/*'

jobs:

  bazel-setup:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Bazel
        uses: bazel-contrib/setup-bazel@0.14.0
        with:
          bazelisk-cache: true
          disk-cache: ${{ github.workflow }}
          repository-cache: true
    
  update-requirements-lock:
    runs-on: ubuntu-latest
    permissions:
      contents: write  # Required to push changes
    needs:
      - bazel-setup
    steps:
      - name: Update requirements lock with Bazel
        run: bazel run //:requirements.update

      - name: Commit Changes
        uses: EndBug/add-and-commit@v9
        with:
          author_name: Bazel Requirements
          author_email: bazel@example.com
          message: "Update requirements lockfile"

  terraform-plan:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
      pull-requests: write
    needs:
      - bazel-setup
      - update-requirements-lock
    steps:
      - name: Build with Bazel
        run: bazel build //src:deployment_archive

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: arn:aws:iam::911866154296:role/GithubActionsTerraform-deploy-dev-desktop
          aws-region: eu-north-1

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform Init
        run: terraform init

      - name: Terraform Plan
        run: terraform plan -out=tfplan

      - name: Comment Plan on PR
        uses: borchero/terraform-plan-comment@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          planfile: tfplan
