name: Pull Request

on:
  pull_request:
    paths:
      - '**/*'

jobs:

  update-requirements-and-terraform-plan:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: write # To make a commit
      pull-requests: write # To post a comment
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          repository: ${{ github.event.pull_request.head.repo.full_name }}
          ref: ${{ github.event.pull_request.head.ref }}

      - name: Set up Bazel
        uses: bazel-contrib/setup-bazel@0.14.0
        with:
          bazelisk-cache: true
          disk-cache: ${{ github.workflow }}
          repository-cache: true
    
      - name: Update requirements lock with Bazel
        run: bazel run //:requirements.update

      - name: Commit Changes
        uses: EndBug/add-and-commit@v9
        with:
          author_name: Bazel Requirements
          author_email: bazel@example.com
          message: "Update requirements lockfile"

      - name: Build with Bazel
        run: bazel build //src:deployment_archive

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: arn:aws:iam::911866154296:role/GithubActionsTerraform-deploy-dev-desktop
          aws-region: eu-north-1

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform Init
        run: terraform init

      - name: Commit Terraform Changes
        uses: EndBug/add-and-commit@v9
        with:
          author_name: Terraform lockfile
          author_email: terraform@example.com
          message: "Update terraform lockfile"

      - name: Terraform Plan
        run: terraform plan -out=tfplan

      - name: Comment Plan on PR
        uses: borchero/terraform-plan-comment@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          planfile: tfplan
